### ISSUE TITLE
Is this cookbook still up-to-date?

### ISSUE THREAD

**Issue by patcon** [msonnabaum/chef-xhprof#1]
Hey dude,

Is this getting out of date with Megalon's xhprof cookbook? If so, I'd suggest this might be a reason to look into using @yfeldblum's [Librarian gem](https://github.com/applicationsonline/librarian) to manage cookbooks, since it makes for a pretty effortless workflow that ensures external cookbooks are the canonical ones

Possibly a good frame of reference for using librarian:
https://github.com/FLOSolutions/fga-chef-repo#readme
("Project-Specific Notes" is the unique part)

Cheers

**Comment by patcon** [comment]
And to explain, I'm only asking because I'd like to use your cookbook as the one that's pulled into myplanet's vagrant dev environment, but I'll need to host my own if it's not current :)

**Comment by msonnabaum** [comment]
Did you notice any differences? They look the same to me. THis cookbook should rarely update.

That said, I think I've been ok at updating the main repos before megalodon (just did that with phpunit) so it's fine to trust these to be recent.

I played with librarian, which I like the idea of, but had some trouble getting it to work. Maybe I'll give it another shot sometime.

**Comment by patcon** [comment]
Ah, shit, was looking too quickly at the differing commit logs. I guess you can blame the fact that I'm probably overly antsy to see people move toward using librarian :P

sorry man
